function fig = init_graph(fig_num)
%init_graph Sets focus on the specified figure and
%           eastablishes a common template.

    fig = figure(fig_num);

    set(gcf                                      , ...
     'DefaultAxesFontName', 'Times New Roman'    , ...
     'DefaultAxesFontSize', 11                   , ...
     'DefaultTextFontname', 'Times New Roman'    , ...
     'DefaultTextFontSize', 11                   , ...
     'PaperUnits' , 'Centimeters'                , ...
     'Units' , 'Centimeters'                     , ...
     'PaperOrientation' , 'Portrait'             , ...
     'PaperPositionMode' , 'auto'                , ...
     'Position', [2 2 8.3 4.5]);

end

